apiVersion: v1
kind: Service
metadata:
  name: tasks-service
  labels:
    app: tasks-app
spec:
  type: ClusterIP
  selector:
    app: tasks-app
  ports:
    - name: http
      port: 5300
      targetPort: 5300
