apiVersion: v1
kind: ConfigMap
metadata:
  name: tasks-config
  namespace: default
  labels:
    app: tasks-api
data:
  # Port HTTP utilis√© par l'application Spring Boot "tasks"
  SERVER_PORT: "5300"


