apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tasks-ingress
  namespace: default
  annotations:
    # Exemple pour nginx-ingress. Ã€ adapter selon ton ingress controller.
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: tasks.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                # Doit correspondre exactement au nom du Service Kubernetes
                name: tasks-api
                port:
                  number: 5300
