apiVersion: v1
kind: Service
metadata:
  name: tasks-api
  namespace: default
  labels:
    app: tasks-api
spec:
  selector:
    app: tasks-api
  type: ClusterIP
  ports:
    - name: http
      port: 5300
      targetPort: 5300


